remote-theme: bpgs/redlab
title: Noch eine Github-Site
description: Eine Seite mit dem redlab-Theme von Ben Balter
author:
  name: BPGS
  twitter: schlamutzelnase

repository: bpgs/test-github-pages
logo: "/assets/img/headshot.jpg"

twitter:
  username: "@benbalter"  
  
nav_pages:
  - index.html
  - talks.md
  - about.md
  - contact.md

footer_pages:
  - books-for-geeks.html
  - fine-print.md


